# V4-style gap screens for ISSUE11 V1 (Design Room). Returns dict name->html.
A='assets/'
LOGO11=A+'0bb93fbeaae4f5c1075c630112490891.png'; WORD=A+'047dac70daad7904d7f244776943629a.png'; WORDW=A+'87dc13ab6fc6899760d14f4e933985e4.png'
ELEVEN_CREAM=A+'182af8e00ccd25d2a6ff67b804dffea2.png'; ELEVEN_W=A+'96d8e919f7e43e3001de6f6b3c434569.png'
IMG=[A+x for x in ['2297423261dd37d2991e798355bef3f0.jpg','300083f531dce2c517d604c08f3f0cfd.jpg','4d6b051f13ff97ce97394d77b8939b3d.jpg','e09a3256e50c1de74e3de92eabc64351.jpg','6203d1401228d8877bf5668c10524f63.jpg','3e3e149499bcf2f95a3dd5f9c51a9f7f.jpg','f824ad2af46b9b9264ed8b335ac2587e.jpg','4e1b7209ec4769c3f3c2cdb83bbbf598.jpg','e4aef317de958c0a82a281641a5b6c9e.jpg','2af8cfb2572710e5c45ba17f6f675389.jpg','55d4ceea9086f4174d346bd771b4192f.jpg']]
MONO="font-family: 'IBM Plex Mono', monospace; font-size: 11px; letter-spacing: 0.03em; text-transform: uppercase;"
BIG="font-family: 'Archivo Black', sans-serif; letter-spacing: -0.065em; line-height: 0.86; text-transform: uppercase;"
ARROW='<svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M0 7h20M14 1l6 6-6 6"></path></svg>'
BACK='<a href="#" aria-label="Back" style="display: flex; width: 40px; height: 40px; align-items: center; justify-content: center; color: currentColor"><svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M22 7H2M8 1L2 7l6 6"></path></svg></a>'
GLASS="background: linear-gradient(160deg, rgba(255,255,255,0.24), rgba(255,255,255,0.06)); border: 1px solid rgba(255,255,255,0.5); box-shadow: inset 0 1px 0.5px rgba(255,255,255,0.65), 0 8px 24px rgba(0,0,0,0.25); backdrop-filter: blur(16px) saturate(180%); -webkit-backdrop-filter: blur(16px) saturate(180%);"
def btn(label,dark=True,arrow=True,flex=False,extra=''):
    bg='background: #0d0d0d; color: #FFFFFF;' if dark else 'background: #F2F2F2; color: #0d0d0d;'
    return f'<a href="#" data-b="{label}" style="display: flex; align-items: center; justify-content: center; gap: 10px; height: 58px; border-radius: 29px; {bg} text-decoration: none; {MONO} font-size: 12px; {"flex: 1;" if flex else ""}{extra}">{label}{(" "+ARROW) if arrow else ""}</a>'
def wbtn(label):
    return f'<a href="#" data-b="{label}" style="display: flex; align-items: center; justify-content: center; gap: 10px; height: 58px; border-radius: 29px; background: #FFFFFF; color: #0d0d0d; text-decoration: none; {MONO} font-size: 12px">{label} {ARROW}</a>'
def chip(t,on=False,col='#0d0d0d'):
    st=f'background: {col}; color: #FFFFFF;' if on else 'background: #F2F2F2; color: #0d0d0d;'
    return f'<span data-chip style="display: inline-flex; align-items: center; height: 36px; padding: 0 14px; border-radius: 18px; {st} {MONO} cursor: pointer">{t}</span>'
def shell(inner,bg='#FFFFFF',fg='#0d0d0d'):
    return f'<div style="position: relative; width: 100%; height: 100%; box-sizing: border-box; overflow-y: auto; overflow-x: hidden; scrollbar-width: none; background: {bg}; color: {fg}; font-family: \'Archivo Narrow\', sans-serif">{inner}</div>'
def q(n,head,body,cta='NEXT',second=None,note=''):
    bars=''.join(f'<span style="flex: 1; height: 3px; border-radius: 2px; background: {"#0d0d0d" if i<n else "rgba(13,13,13,0.15)"}"></span>' for i in range(9))
    foot=f'<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; gap: 8px">{btn(second,False,False,True) if second else ""}{btn(cta,True,True,True)}</div>'
    return shell(f'''<div style="position: absolute; left: 16px; right: 16px; top: 22px; display: flex; align-items: center; gap: 10px">{BACK}<div style="flex: 1; display: flex; gap: 4px">{bars}</div><span style="{MONO}">{n:02d}/09</span></div>
<div style="position: absolute; left: 16px; right: 16px; top: 84px"><div style="{MONO}">Question {n:02d}{(" · "+note) if note else ""}</div><div style="{BIG} font-size: 46px; margin-top: 8px">{head}</div></div>
<div style="position: absolute; left: 16px; right: 16px; top: 300px; bottom: 110px; overflow-y: auto">{body}</div>{foot}''')
def field(ph,val=''):
    return f'<div contenteditable="true" data-ph="{ph}" style="padding: 18px; background: #F7F7F7; min-height: 120px; box-sizing: border-box; font-size: 19px; line-height: 1.45; outline: none">{val}</div>'
def opt(t,sub='',on=False):
    subdiv=('<div style="font-size: 15px; color: #555; margin-top: 4px">'+sub+'</div>') if sub else ''
    return f'<a href="#" data-opt style="display: block; padding: 16px 0; border-top: 1px solid rgba(13,13,13,0.15); color: #0d0d0d; text-decoration: none"><div style="display: flex; justify-content: space-between; align-items: center"><span style="font-family: \'Archivo Black\', sans-serif; letter-spacing: -0.05em; font-size: 24px; text-transform: uppercase">{t}</span><span class="dot" style="width: 22px; height: 22px; border-radius: 50%; border: 1.5px solid #0d0d0d; background: {"#0d0d0d" if on else "transparent"}"></span></div>{subdiv}</a>'
S={}
S['q01']=q(1,'What should<br>we call our<br>cover star?',field('Your first name','Megan')+f'<div style="{MONO} margin-top: 12px; color: #666">It goes on the cover of your Issue.</div>')
S['q03']=q(3,'What do you<br>want most<br>this year?',''.join(opt(t,s,i==0) for i,(t,s) in enumerate([('Financial freedom','Money that gives me choices'),('A home I love','Space that feels like me'),('Real love','Being chosen, choosing back'),('My own thing','A business, a studio, a name'),('Peace','Calm, health, nothing to prove')])))
S['q04']=q(4,'Pick what<br>feels like<br>her.',f'<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 6px">'+''.join(f'<a href="#" data-pick style="position: relative; display: block; height: 130px; overflow: hidden; {"outline: 3px solid #0d0d0d; outline-offset: 2px;" if i in (0,2,5) else ""}"><img src="{IMG[i]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"></a>' for i in range(9))+'</div>',cta='NEXT · 3 PICKED',note='Your World')
S['q05']=q(5,'How do you<br>want to<br>practice?',''.join(opt(t,s,i==2) for i,(t,s) in enumerate([('Listen','Audio, eyes closed'),('Watch','Immersive video'),('Both','Mix it up')]))+f'<div style="{MONO} margin: 20px 0 10px">How long?</div><div style="display: flex; gap: 8px">{chip("5 min",True)}{chip("10 min")}{chip("20 min")}</div>',note='Audio')
S['q06']=q(6,'How do you<br>want to feel<br>every day?',f'<div style="display: flex; flex-wrap: wrap; gap: 8px">'+''.join(chip(t,t in ('Unbothered','Rich','Chosen'),'#F65AAD') for t in ['Unbothered','Rich','Chosen','Free','Powerful','Soft','Seen','Calm','Magnetic'])+'</div>')
S['q08']=q(8,'Name one<br>thing you<br>already made<br>happen.',field('e.g. I moved cities on my own.','I left the job that made me small.')+f'<div style="{MONO} margin-top: 12px; color: #666">Your first proof. It opens your Issue.</div>',note='Proof')
S['q09']=q(9,'One small<br>step this<br>week?',field('Something small that the future you would do.','Book a viewing for a place by the sea.')+f'<div style="{MONO} margin-top: 12px; color: #666">This becomes your first move.</div>',cta='BUILD MY ISSUE')
S['how']=shell(f'''<div style="padding: 30px 16px 0"><div style="{MONO}">How ISSUE11 works</div><div style="{BIG} font-size: 44px; margin-top: 8px">You're not<br>just making a<br>vision board.</div><div style="font-size: 17px; line-height: 1.4; margin-top: 12px">You're creating an Issue around the person you're becoming.</div></div>
<div style="padding: 18px 16px 120px">'''+''.join(f'<div style="display: flex; gap: 14px; padding: 14px 0; border-top: 1px solid rgba(13,13,13,0.15)"><span style="{MONO} width: 22px">0{i+1}</span><div><div style="{BIG} font-size: 28px; letter-spacing: -0.05em">{h}</div><div style="font-size: 15px; color: #444; margin-top: 4px">{t}</div></div></div>' for i,(h,t) in enumerate([('Desire','Tell us what you want.'),('Imagine','Turn it into images, words and audio.'),('Embody','Practice thinking, feeling and acting like her.'),('Become','Add proof as your future becomes your life.')]))+f'</div><div style="position: absolute; left: 16px; right: 16px; bottom: 30px">{btn("LET’S START")}</div>')
S['meet']=shell(f'''<img src="{ELEVEN_CREAM}" alt="" style="position: absolute; left: 50%; top: 70px; height: 120px; width: auto; transform: translateX(-50%)">
<div style="position: absolute; left: 20px; right: 20px; top: 240px"><div style="{MONO}">Meet</div><div style="{BIG} font-size: 52px; margin-top: 8px">Lucky<br>Star ★</div><div style="font-size: 17px; line-height: 1.45; margin-top: 16px; color: #F5EEE0">Your AI manifestation guide. Lucky Star learns what you're working toward and helps you create your Issue, build your practice and decide what to do next.</div><div style="font-family: 'Archivo Black', sans-serif; font-size: 18px; letter-spacing: -0.03em; margin-top: 14px">You stay in control. Nothing is added or changed unless you approve it.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 12px"><label style="display: flex; gap: 12px; align-items: flex-start; font-size: 14px; line-height: 1.4; color: rgba(245,238,224,0.85); cursor: pointer"><input type="checkbox" id="consent" checked style="width: 20px; height: 20px; accent-color: #F65AAD; margin-top: 2px">Your answers are sent to an AI service to build your Issue. It doesn't train on them or keep them. You can turn AI off in Settings.</label>{wbtn("I'M IN")}<div data-b="PRIVACY" style="text-align: center; {MONO} color: rgba(245,238,224,0.6); cursor: pointer">Read our privacy policy</div></div>''',bg='#0d0d0d',fg='#F5EEE0')
S['reveal']=shell(f'''<img src="{IMG[8]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.15), rgba(0,0,0,0) 30%, rgba(0,0,0,0.7))"></div>
<div style="position: absolute; left: 16px; right: 16px; top: 26px; height: 190px; display: flex; justify-content: center"><img src="{WORDW}" alt="ISSUE11" style="display: block; height: 100%; width: auto"></div>
<div style="position: absolute; left: 16px; right: 16px; top: 228px; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.7); display: flex; justify-content: space-between; {MONO} color: #fff"><span>Vol. 01</span><span>Autumn 2026</span></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; color: #fff; display: flex; flex-direction: column; gap: 14px"><div style="{MONO}">Your first Issue is ready</div><div style="{BIG} font-size: 58px">The Megan<br>Issue</div><div style="font-size: 16px; line-height: 1.4">Financial freedom · A home by the sea · Unbothered</div>{wbtn("OPEN MY ISSUE")}</div>''',bg='#0d0d0d',fg='#fff')
S['notif']=shell(f'''<div style="position: absolute; left: 50%; top: 120px; transform: translateX(-50%) rotate(-6deg)"><span style="position: relative; display: block; width: 120px; height: 120px; border-radius: 33px; overflow: hidden; background: #F5EEE0; border: 3px solid #fff; box-shadow: 0 6px 14px rgba(0,0,0,0.25)"><img src="{LOGO11}" alt="" style="position: absolute; left: 50%; top: 50%; height: 76%; transform: translate(-50%,-50%)"></span></div>
<div style="position: absolute; left: 20px; right: 20px; top: 300px; text-align: center"><div style="{MONO}">One gentle nudge a day</div><div style="{BIG} font-size: 44px; margin-top: 10px">Get your<br>issue every<br>morning?</div><div style="font-size: 16px; line-height: 1.4; margin-top: 14px; color: #444">A line from your Issue and tonight's session. No spam, ever.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 10px">{btn("YES, EVERY MORNING")}<div data-b="NOT NOW" style="text-align: center; {MONO} cursor: pointer; padding: 10px">Not now</div></div>''')
S['paywall']=shell(f'''<div style="position: relative; height: 420px; overflow: hidden"><img src="{IMG[2]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><img src="{ELEVEN_W}" alt="" style="position: absolute; left: 50%; top: 50%; height: 300px; transform: translate(-50%,-50%); filter: drop-shadow(0 10px 30px rgba(0,0,0,0.25))"><a href="#" aria-label="Close" data-b="CLOSE" style="position: absolute; right: 16px; top: 22px; display: flex; width: 40px; height: 40px; border-radius: 50%; align-items: center; justify-content: center; color: #fff; {GLASS}"><svg width="14" height="14" viewBox="0 0 14 14" stroke="currentColor" stroke-width="1.8"><path d="M1 1l12 12M13 1L1 13"/></svg></a></div>
<div style="padding: 18px 16px 0"><div style="{MONO}">ISSUE11 Membership</div><div style="{BIG} font-size: 40px; margin-top: 6px">Keep becoming<br>her.</div><div style="font-size: 15px; line-height: 1.5; margin-top: 10px">Your Issue, every Audio session, Scribe, Your World and new pages every month.</div>
<div style="display: flex; gap: 8px; margin-top: 16px"><a href="#" data-plan style="flex: 1; padding: 14px; border: 3px solid #0d0d0d; color: #0d0d0d; text-decoration: none"><div style="{MONO}">Yearly</div><div style="font-family: 'Archivo Black', sans-serif; font-size: 22px; margin-top: 6px">PRICE TBD</div></a><a href="#" data-plan style="flex: 1; padding: 14px; border: 1px solid rgba(13,13,13,0.2); color: #0d0d0d; text-decoration: none"><div style="{MONO}">Monthly</div><div style="font-family: 'Archivo Black', sans-serif; font-size: 22px; margin-top: 6px">PRICE TBD</div></a></div>
<div style="font-size: 12px; color: #666; line-height: 1.4; margin-top: 10px">Renews automatically until cancelled. Cancel anytime in Settings. (Final wording, prices and any trial: Revenue + Megan.)</div></div>
<div style="padding: 14px 16px 30px; display: flex; flex-direction: column; gap: 10px">{btn("CONTINUE")}<div style="display: flex; justify-content: center; gap: 16px; {MONO} font-size: 10px; color: #555"><span data-b="RESTORE" style="cursor: pointer">Restore</span><span>Terms</span><span>Privacy</span></div></div>''')
S['write']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 22px 16px 0">{BACK}<span style="{MONO}">Scribe · Oct 03 · P.08</span></div>
<div style="padding: 14px 16px 0"><div style="{MONO} color: #666">Today's prompt</div><div style="{BIG} font-size: 34px; margin-top: 6px">Who is she, one<br>year from now?</div></div>
<div contenteditable="true" style="margin: 16px; min-height: 360px; font-size: 19px; line-height: 1.5; outline: none">She wakes up before her alarm. The light comes in off the water. <span style="background: #FCD2DD">She doesn't check her bank balance anymore</span>; she checks in with herself.<span style="display: inline-block; width: 2px; height: 22px; background: #F65AAD; vertical-align: -4px; margin-left: 2px"></span></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; gap: 8px">{btn("SAY IT INSTEAD",False,False,True)}{btn("SAVE TO MY ISSUE",True,False,True)}</div>''')
S['proof']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 22px 16px 0">{BACK}<span style="{MONO}">Add proof</span></div>
<div style="padding: 14px 16px 0"><div style="{MONO} color: #666">You wrote, 6 months ago</div><div style="font-family: Georgia, serif; font-size: 22px; line-height: 1.3; margin-top: 8px">“A home by the sea.”</div><div style="{BIG} font-size: 40px; margin-top: 18px">What<br>happened?</div></div>
<div style="padding: 14px 16px 0">{field("Tell it like a headline.","I signed the lease. I can hear the waves.")}<a href="#" data-b="PHOTO" style="display: flex; align-items: center; justify-content: center; height: 110px; margin-top: 10px; border: 1.5px dashed #BDBDBD; color: #666; text-decoration: none; {MONO}">+ Add a photo</a></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px">{btn("ADD PROOF")}</div>''')
S['proofdone']=shell(f'''<img src="{ELEVEN_CREAM}" alt="" style="position: absolute; left: 50%; top: 50%; height: 1000px; transform: translate(-50%,-50%)">
<div style="position: absolute; left: 0; right: 0; bottom: 0; height: 420px; background: linear-gradient(180deg, rgba(212,8,6,0), #D40806 38%)"></div><div style="position: absolute; left: 16px; right: 16px; bottom: 30px; color: #F5EEE0; display: flex; flex-direction: column; gap: 14px"><div style="{MONO}">Proof · Oct 03</div><div style="{BIG} font-size: 64px">It's<br>real.</div><div style="font-size: 17px">Added to your Issue as page 08.</div>{wbtn("SEE IT IN MY ISSUE")}</div>''',bg='#D40806',fg='#F5EEE0')
S['page']=shell(f'''<div style="position: relative; height: 100%"><img src="{IMG[6]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.35), rgba(0,0,0,0) 25%, rgba(0,0,0,0) 45%, rgba(0,0,0,0.75))"></div>
<div style="position: absolute; left: 16px; right: 16px; top: 22px; display: flex; justify-content: space-between; align-items: center; color: #fff"><a href="#" aria-label="Back" style="display: flex; width: 44px; height: 44px; border-radius: 50%; align-items: center; justify-content: center; color: #fff; {GLASS}"><svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 7H2M8 1L2 7l6 6"/></svg></a><span style="{MONO}">P.07 / 11</span></div>
<div style="position: absolute; left: 16px; right: 16px; top: 120px; color: #fff"><div style="{MONO}">Feature</div><div style="{BIG} font-size: 60px; margin-top: 8px">The<br>morning<br>she wakes<br>up rich</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 112px; color: #fff; font-size: 17px; line-height: 1.45">6am. Ocean air. Nothing to prove, everything to build.</div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 26px; display: flex; align-items: center; gap: 10px; height: 64px; padding: 0 6px 0 18px; border-radius: 32px; background: #fff; box-shadow: 0 10px 30px rgba(246,90,173,0.25)"><span style="position: relative; display: block; width: 34px; height: 34px; border-radius: 10px; overflow: hidden; background: #F5EEE0; transform: rotate(-6deg); flex-shrink: 0"><img src="{LOGO11}" alt="" style="position: absolute; left: 50%; top: 50%; height: 76%; transform: translate(-50%,-50%)"></span><input id="pageprompt" placeholder="Change this page… e.g. make it softer" style="flex: 1; min-width: 0; border: 0; outline: 0; font-family: 'Archivo Narrow', sans-serif; font-size: 16px; background: transparent"><a href="#" data-b="APPLY" style="display: flex; width: 50px; height: 50px; border-radius: 50%; align-items: center; justify-content: center; background: #F65AAD; color: #0d0d0d">{ARROW}</a></div></div>''',bg='#0d0d0d',fg='#fff')
rows=[('App icon','icons'),('Your ritual','streak'),('Notifications','notif'),('Lucky Star & AI','meet'),('Membership','paywall'),('Privacy policy',''),('Sign out',''),('Delete account','delete')]
S['you']=shell(f'''<div style="padding: 30px 16px 0; display: flex; gap: 14px; align-items: center"><span style="width: 64px; height: 64px; border-radius: 50%; overflow: hidden; position: relative; flex-shrink: 0"><img src="{IMG[9]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"></span><div><div style="{BIG} font-size: 40px">Megan</div><div style="{MONO} margin-top: 6px">Vol. 01 · 12 day streak</div></div></div>
<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; padding: 22px 16px 6px">'''+''.join(f'<div style="background: #F2F2F2; padding: 12px"><div style="font-family: \'Archivo Black\', sans-serif; font-size: 28px">{n}</div><div style="{MONO} margin-top: 4px">{l}</div></div>' for n,l in [('7','Pages'),('3','Proofs'),('12','Days')])+f'''</div>
<div style="padding: 10px 16px 120px">'''+''.join(f'<a href="#" data-go2="{g}" style="display: flex; justify-content: space-between; align-items: center; padding: 18px 0; border-top: 1px solid rgba(13,13,13,0.12); color: {"#D40806" if t=="Delete account" else "#0d0d0d"}; text-decoration: none; font-family: \'Archivo Black\', sans-serif; font-size: 20px; letter-spacing: -0.03em; text-transform: uppercase">{t}<span style="{MONO}">→</span></a>' for t,g in rows)+'</div>')
S['delete']=shell(f'''<div style="padding: 22px 16px 0">{BACK}</div><div style="padding: 20px 16px"><div style="{MONO} color: #D40806">Delete account</div><div style="{BIG} font-size: 44px; margin-top: 8px">Are you<br>sure?</div><div style="font-size: 16px; line-height: 1.5; margin-top: 14px">This permanently deletes your account, your Issue, Scribe entries, Your World and proofs. It can't be undone. Your App Store subscription is managed by Apple; cancel it there so you're not charged again.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 10px">{btn("DELETE MY ACCOUNT",True,False,False,"background: #D40806;")}<div data-b="KEEP" style="text-align: center; {MONO} cursor: pointer; padding: 10px">Keep my account</div></div>''')

# ===== Batch 2 (Megan: "Add it all please") =====
def ptile(img,label,mins,h=210):
    return f'<a href="#" data-sess style="position: relative; display: block; height: {h}px; overflow: hidden; color: #FFFFFF; text-decoration: none"><img src="{img}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0) 40%, rgba(0,0,0,0.65))"></div><span style="position: absolute; left: 10px; top: 10px; {MONO}">{mins}</span><span style="position: absolute; left: 10px; right: 10px; bottom: 10px; {BIG} font-size: 22px; letter-spacing: -0.05em">{label}</span></a>'
cats=['All','Confidence','Money','Love','Calm','Sleep']
S['explore']=shell(f'''<div style="padding: 30px 16px 10px; display: flex; justify-content: space-between; align-items: flex-end"><div style="{BIG} font-size: 56px">Explore</div><div style="{MONO}">32 sessions</div></div>
<div style="display: flex; gap: 8px; padding: 0 16px 14px; overflow-x: auto; scrollbar-width: none">'''+''.join(chip(c,i==0) for i,c in enumerate(cats))+f'''</div>
<a href="#" data-sess style="position: relative; display: block; height: 380px; margin: 0 8px; overflow: hidden; color: #fff; text-decoration: none"><img src="{IMG[5]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.2), rgba(0,0,0,0) 30%, rgba(0,0,0,0.7))"></div><span style="position: absolute; left: 14px; top: 14px; display: inline-flex; align-items: center; height: 32px; padding: 0 12px; border-radius: 16px; {MONO} {GLASS}">New this week</span><div style="position: absolute; left: 16px; right: 16px; bottom: 16px"><div style="{MONO}">Self concept · Video · 12 min</div><div style="{BIG} font-size: 46px; margin-top: 6px">Become<br>her.</div></div></a>
<div style="display: flex; justify-content: space-between; padding: 26px 16px 10px; {MONO}"><span>Collections</span><span data-b="SEE ALL" style="cursor: pointer">See all</span></div>
<div style="display: flex; gap: 8px; padding: 0 16px; overflow-x: auto; scrollbar-width: none">'''+''.join(f'<a href="#" data-coll style="position: relative; flex: 0 0 150px; height: 190px; overflow: hidden; color: #fff; text-decoration: none; background: {bg}"><img src="{im}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; opacity: .85"><span style="position: absolute; left: 10px; bottom: 10px; {BIG} font-size: 20px; letter-spacing: -0.05em">{t}</span><span style="position: absolute; left: 10px; top: 10px; {MONO}">{n} sessions</span></a>' for t,n,im,bg in [('Rich is a feeling',8,IMG[3],'#000'),('Soft power',6,IMG[1],'#000'),('Chosen',5,IMG[7],'#000'),('Unbothered',7,IMG[0],'#000')])+f'''</div>
<div style="padding: 26px 16px 10px; {MONO}">For your goals · Wealth · Love · Travel</div>
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; padding: 0 16px 130px">'''+''.join(ptile(IMG[i],t,m) for i,t,m in [(2,'Money loves me','5 min'),(4,'The soft life','10 min'),(6,'Booked & chosen','8 min'),(9,'Sleep like her','20 min')])+'</div>')
S['collection']=shell(f'''<div style="position: relative; height: 380px; overflow: hidden; color: #fff"><img src="{IMG[3]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.3), rgba(0,0,0,0) 30%, rgba(0,0,0,0.7))"></div><div style="position: absolute; left: 16px; top: 22px"><a href="#" aria-label="Back" style="display: flex; width: 44px; height: 44px; border-radius: 50%; align-items: center; justify-content: center; color: #fff; {GLASS}"><svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 7H2M8 1L2 7l6 6"/></svg></a></div><div style="position: absolute; left: 16px; right: 16px; bottom: 16px"><div style="{MONO}">Collection · 8 sessions</div><div style="{BIG} font-size: 50px; margin-top: 6px">Rich is<br>a feeling</div></div></div>
<div style="padding: 6px 16px 40px">'''+''.join(f'<a href="#" data-sess style="display: flex; gap: 14px; align-items: center; padding: 14px 0; border-bottom: 1px solid rgba(13,13,13,0.12); color: #0d0d0d; text-decoration: none"><span style="{MONO} width: 22px">0{i+1}</span><div style="flex: 1"><div style="font-family: \'Archivo Black\', sans-serif; letter-spacing: -0.04em; font-size: 20px; text-transform: uppercase">{t}</div><div style="{MONO} color: #666; margin-top: 4px">{k}</div></div><span style="width: 40px; height: 40px; border-radius: 50%; background: #F65AAD; display: flex; align-items: center; justify-content: center"><svg width="12" height="14" viewBox="0 0 12 14"><path d="M1 1l10 6-10 6z" fill="#0d0d0d"/></svg></span></a>' for i,(t,k) in enumerate([('Rich is a feeling','Affirmations · Audio · 3 min'),('Money loves me','Visualization · Audio · 5 min'),('The first million','Visualization · Video · 12 min'),('Receiving','Breathwork · Audio · 8 min'),('Abundant morning','Affirmations · Audio · 5 min')]))+'</div>')
S['after']=shell(f'''<div style="position: absolute; inset: 0; background: radial-gradient(closest-side at 50% 30%, rgba(246,90,173,0.45), rgba(252,210,221,0.3) 50%, rgba(255,255,255,0) 80%)"></div>
<div style="position: relative; padding: 60px 20px 0; text-align: center"><div style="{MONO}">Session complete · Become her · 12 min</div><div style="{BIG} font-size: 50px; margin-top: 12px">How do you<br>feel now?</div></div>
<div style="position: relative; display: flex; flex-wrap: wrap; gap: 8px; justify-content: center; padding: 22px 20px 0">'''+''.join(chip(t,t=='Powerful','#F65AAD') for t in ['Calm','Powerful','Lighter','Ready','Emotional','Magnetic'])+f'''</div>
<div style="position: relative; padding: 22px 16px 0"><div style="{MONO} margin-bottom: 8px">One line from her</div>{field("What did future you say?","I don't rush. Everything I want is already moving toward me.")}</div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; gap: 8px">{btn("SKIP",False,False,True)}{btn("SAVE TO SCRIBE",True,False,True)}</div>''')
S['proofs']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 22px 16px 0">{BACK}<span style="{MONO}">3 proofs</span></div>
<div style="padding: 10px 16px 14px"><div style="{BIG} font-size: 56px">Past<br>proof</div><div style="font-size: 16px; color: #444; margin-top: 8px">What you wrote, and what happened.</div></div>
<div style="padding: 0 16px 140px; display: flex; flex-direction: column; gap: 10px">'''+''.join(f'<div style="display: flex; gap: 12px; background: {bg}; color: {fg}; padding: 14px"><div style="position: relative; width: 96px; height: 120px; flex-shrink: 0; overflow: hidden"><img src="{im}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"></div><div style="flex: 1; display: flex; flex-direction: column; gap: 6px"><div style="{MONO} opacity: .75">You wrote · {ago}</div><div style="font-family: Georgia, serif; font-size: 16px">“{w}”</div><div style="{MONO} opacity: .75; margin-top: 4px">Now · {d}</div><div style="font-family: \'Archivo Black\', sans-serif; letter-spacing: -0.04em; font-size: 19px; line-height: 1; text-transform: uppercase">{n}</div></div></div>' for bg,fg,im,ago,w,d,n in [('#D40806','#F5EEE0',IMG[1],'6 months ago','A home by the sea','Oct 03','I signed the lease. I can hear the waves.'),('#FCD2DD','#0d0d0d',IMG[2],'8 months ago','I get paid for my taste','Sep 12','First styling client. Paid in full.'),('#0d0d0d','#F5EEE0',IMG[7],'Onboarding','I left the job that made me small','Your first proof','It opened your Issue.')])+f'</div><div style="position: absolute; left: 16px; right: 16px; bottom: 30px">{btn("+ ADD PROOF",True,False)}</div>')
COVERMARK='<div style="position: absolute; left: 16px; right: 16px; top: 70px; height: 170px; display: flex; justify-content: center"><img src="'+WORDW+'" alt="" style="height: 100%; width: auto"></div>'
PAGES=[(IMG[8],'The Megan<br>Issue','Cover · Autumn 2026'),(IMG[3],'Rich is<br>a feeling','Feature · P.02'),(IMG[1],'A home<br>by the sea','Your world · P.03'),(IMG[6],'The morning<br>she wakes<br>up rich','Scribe · P.04'),(IMG[0],'Same girl.<br>Higher<br>standards.','Scribe · P.05'),(IMG[2],'It’s<br>real.','Proof · P.06'),(IMG[5],'Become<br>her.','Next issue · P.07')]
S['reader']=shell(f'''<div id="readerTrack" style="position: absolute; inset: 0; display: flex; overflow-x: auto; scroll-snap-type: x mandatory; scrollbar-width: none">'''+''.join(f'<div style="position: relative; flex: 0 0 100%; height: 100%; scroll-snap-align: start; overflow: hidden; color: #fff"><img src="{im}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.35), rgba(0,0,0,0) 30%, rgba(0,0,0,0) 50%, rgba(0,0,0,0.7))"></div>{COVERMARK if i==0 else ""}<div style="position: absolute; left: 16px; right: 16px; bottom: 70px"><div style="{MONO}">{k}</div><div style="{BIG} font-size: 54px; margin-top: 8px">{h}</div></div></div>' for i,(im,h,k) in enumerate(PAGES))+f'''</div>
<div style="position: absolute; left: 16px; right: 16px; top: 22px; display: flex; justify-content: space-between; align-items: center; color: #fff; z-index: 2"><a href="#" aria-label="Back" style="display: flex; width: 44px; height: 44px; border-radius: 50%; align-items: center; justify-content: center; color: #fff; {GLASS}"><svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 7H2M8 1L2 7l6 6"/></svg></a><span id="readerCount" style="{MONO}">01 / {len(PAGES):02d}</span><a href="#" data-b="EDIT" style="display: inline-flex; align-items: center; height: 34px; padding: 0 14px; border-radius: 17px; color: #fff; text-decoration: none; {MONO} {GLASS}">Edit page</a></div>
<div style="position: absolute; left: 0; right: 0; bottom: 26px; text-align: center; {MONO} color: rgba(255,255,255,0.75); z-index: 2">Swipe to turn the page →</div>''',bg='#0d0d0d',fg='#fff')
PAT={'none':'none','waves':'repeating-radial-gradient(circle at 0 100%, transparent 0 14px, currentColor 14px 20px)','zebra':'repeating-linear-gradient(115deg, currentColor 0 10px, transparent 10px 26px, currentColor 26px 30px, transparent 30px 52px)','cheetah':'radial-gradient(ellipse 7px 5px at 20% 30%, currentColor 98%, transparent), radial-gradient(ellipse 6px 8px at 70% 60%, currentColor 98%, transparent), radial-gradient(ellipse 5px 4px at 45% 85%, currentColor 98%, transparent)','hearts':'radial-gradient(circle at 30% 35%, currentColor 5px, transparent 6px), radial-gradient(circle at 45% 35%, currentColor 5px, transparent 6px), conic-gradient(from 135deg at 37.5% 48%, currentColor 90deg, transparent 0)'}
SW=[('#FCD2DD','#0d0d0d'),('#F65AAD','#0d0d0d'),('#D40806','#F5EEE0'),('#4BA551','#F5EEE0'),('#F5EEE0','#0d0d0d'),('#0d0d0d','#F5EEE0'),('#FFFFFF','#0d0d0d')]
S['edit']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 18px 16px 0">{BACK}<span style="{MONO}">Edit · P.04</span><a href="#" data-b="UNDO" style="{MONO} color: #0d0d0d; text-decoration: none">↶ Undo</a></div>
<div id="edPage" style="position: relative; margin: 10px 16px 0; height: 430px; overflow: hidden; background: #FCD2DD; color: #0d0d0d; transition: background .2s">
 <div id="edPat" style="position: absolute; inset: 0; color: rgba(13,13,13,0.18); background-size: 60px 60px; pointer-events: none"></div>
 <div id="edL1" style="position: absolute; left: 0; top: 0; width: 55%; height: 100%; overflow: hidden"><img src="{IMG[6]}" alt="" style="width: 100%; height: 100%; object-fit: cover"></div>
 <div id="edText" style="position: absolute; left: 58%; right: 10px; top: 16px"><div style="{MONO}">Scribe · P.04</div><div contenteditable="true" style="{BIG} font-size: 30px; margin-top: 8px; outline: none">The morning she wakes up rich</div><div contenteditable="true" style="font-size: 13px; line-height: 1.4; margin-top: 10px; outline: none">6am. Ocean air. Nothing to prove, everything to build.</div></div>
 <div id="edStickers" style="position: absolute; inset: 0"></div>
</div>
<div style="padding: 12px 16px 0; display: flex; gap: 6px" id="edTabs">'''+''.join(f'<span data-tab="{t}" style="flex: 1; text-align: center; padding: 8px 0; {MONO} border-bottom: 2px solid {"#0d0d0d" if i==0 else "transparent"}; cursor: pointer">{t}</span>' for i,t in enumerate(['Layout','Color','Sticker','Pattern']))+f'''</div>
<div id="edPanel" style="padding: 12px 16px 0; min-height: 70px">
 <div data-panel="Layout" style="display: flex; gap: 8px">'''+''.join(f'<span data-layout="{i}" style="flex: 1; height: 60px; border: {"2px solid #0d0d0d" if i==0 else "1px solid #ccc"}; display: flex; align-items: center; justify-content: center; {MONO} cursor: pointer">{n}</span>' for i,n in enumerate(['Split','Full bleed','Poster']))+'''</div>
 <div data-panel="Color" style="display: none; gap: 8px; flex-wrap: wrap">'''+''.join(f'<span data-color="{b}|{f}" style="width: 40px; height: 40px; border-radius: 50%; background: linear-gradient(135deg, {b} 50%, {f} 50%); border: 1px solid #ccc; cursor: pointer"></span>' for b,f in SW)+'''</div>
 <div data-panel="Sticker" style="display: none; gap: 8px; flex-wrap: wrap; font-size: 28px">'''+''.join(f'<span data-st="{e}" style="cursor: pointer">{e}</span>' for e in ['💗','✨','💸','🌊','🔑','💋','⭐','🍒'])+f'<span data-st="11" style="cursor: pointer; width: 36px; height: 36px; border-radius: 10px; background: #F5EEE0; display: inline-flex; align-items: center; justify-content: center; transform: rotate(-6deg)"><img src="{LOGO11}" alt="" style="height: 26px"></span></div>\n <div data-panel="Pattern" style="display: none; gap: 8px">'+''.join(f'<span data-pat="{k}" style="flex: 1; height: 44px; border: 1px solid #ccc; display: flex; align-items: center; justify-content: center; {MONO} cursor: pointer">{k}</span>' for k in PAT)+f'''</div>
</div>
<div style="{MONO} color: #888; padding: 6px 16px 0">Tap text to edit · drag stickers · pinch to resize on iPhone</div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 24px">{btn("SAVE PAGE",True,False)}</div>''')
S['offline']=shell(f'''<img src="{ELEVEN_CREAM}" alt="" style="position: absolute; left: 50%; top: 120px; height: 150px; transform: translateX(-50%)">
<div style="position: absolute; left: 20px; right: 20px; top: 320px; text-align: center"><div style="{MONO}">No connection</div><div style="{BIG} font-size: 46px; margin-top: 10px">You're<br>offline.</div><div style="font-size: 16px; line-height: 1.45; margin-top: 14px; color: rgba(245,238,224,0.8)">Your Issue and downloaded sessions still work. New pages and Lucky Star come back when you're online.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 10px">{wbtn("READ MY ISSUE")}<div data-b="RETRY" style="text-align: center; {MONO} color: rgba(245,238,224,0.7); cursor: pointer; padding: 8px">Try again</div></div>''',bg='#0d0d0d',fg='#F5EEE0')
S['empty']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 22px 16px 0">{BACK}<span style="{MONO}">Scribe</span></div>
<div style="padding: 20px 16px 0"><div style="{BIG} font-size: 64px">Notes<br>to self</div></div>
<div style="margin: 30px 16px 0; padding: 26px 18px; border: 1.5px dashed #BDBDBD; text-align: center"><span style="display: inline-block; transform: rotate(-6deg)"><span style="position: relative; display: block; width: 66px; height: 66px; border-radius: 18px; overflow: hidden; background: #F5EEE0; border: 3px solid #fff; box-shadow: 0 8px 20px rgba(0,0,0,0.15)"><img src="{LOGO11}" alt="" style="position: absolute; left: 50%; top: 50%; height: 76%; transform: translate(-50%,-50%)"></span></span><div style="{BIG} font-size: 30px; margin-top: 16px">Your first page<br>is waiting.</div><div style="font-size: 15px; color: #555; margin-top: 10px">Write one line about the woman you're becoming. It goes straight into your Issue.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px">{btn("WRITE MY FIRST LINE")}</div>''')
