# V4-style gap screens for ISSUE11 V1 (Design Room). Returns dict name->html.
A='assets/'
LOGO11=A+'0bb93fbeaae4f5c1075c630112490891.png'; WORD=A+'047dac70daad7904d7f244776943629a.png'; WORDW=A+'87dc13ab6fc6899760d14f4e933985e4.png'
ELEVEN_CREAM=A+'182af8e00ccd25d2a6ff67b804dffea2.png'; ELEVEN_W=A+'96d8e919f7e43e3001de6f6b3c434569.png'
IMG=[A+x for x in ['2297423261dd37d2991e798355bef3f0.jpg','300083f531dce2c517d604c08f3f0cfd.jpg','4d6b051f13ff97ce97394d77b8939b3d.jpg','e09a3256e50c1de74e3de92eabc64351.jpg','6203d1401228d8877bf5668c10524f63.jpg','3e3e149499bcf2f95a3dd5f9c51a9f7f.jpg','f824ad2af46b9b9264ed8b335ac2587e.jpg','4e1b7209ec4769c3f3c2cdb83bbbf598.jpg','e4aef317de958c0a82a281641a5b6c9e.jpg','2af8cfb2572710e5c45ba17f6f675389.jpg','55d4ceea9086f4174d346bd771b4192f.jpg']]
MONO="font-family: 'IBM Plex Mono', monospace; font-size: 11px; letter-spacing: 0.03em; text-transform: uppercase;"
BIG="font-family: 'Archivo Black', sans-serif; letter-spacing: -0.065em; line-height: 0.86; text-transform: uppercase;"
ARROW='<svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M0 7h20M14 1l6 6-6 6"></path></svg>'
BACK='<a href="#" aria-label="Back" style="display: flex; width: 40px; height: 40px; align-items: center; justify-content: center; color: currentColor"><svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M22 7H2M8 1L2 7l6 6"></path></svg></a>'
GLASS="background: linear-gradient(160deg, rgba(255,255,255,0.24), rgba(255,255,255,0.06)); border: 1px solid rgba(255,255,255,0.5); box-shadow: inset 0 1px 0.5px rgba(255,255,255,0.65), 0 8px 24px rgba(0,0,0,0.25); backdrop-filter: blur(16px) saturate(180%); -webkit-backdrop-filter: blur(16px) saturate(180%);"
def btn(label,dark=True,arrow=True,flex=False,extra=''):
    bg='background: #0d0d0d; color: #FFFFFF;' if dark else 'background: #F2F2F2; color: #0d0d0d;'
    return f'<a href="#" data-b="{label}" style="display: flex; align-items: center; justify-content: center; gap: 10px; height: 58px; border-radius: 29px; {bg} text-decoration: none; {MONO} font-size: 12px; {"flex: 1;" if flex else ""}{extra}">{label}{(" "+ARROW) if arrow else ""}</a>'
def wbtn(label):
    return f'<a href="#" data-b="{label}" style="display: flex; align-items: center; justify-content: center; gap: 10px; height: 58px; border-radius: 29px; background: #FFFFFF; color: #0d0d0d; text-decoration: none; {MONO} font-size: 12px">{label} {ARROW}</a>'
def chip(t,on=False,col='#0d0d0d'):
    st=f'background: {col}; color: #FFFFFF;' if on else 'background: #F2F2F2; color: #0d0d0d;'
    return f'<span data-chip style="display: inline-flex; align-items: center; height: 36px; padding: 0 14px; border-radius: 18px; {st} {MONO} cursor: pointer">{t}</span>'
def shell(inner,bg='#FFFFFF',fg='#0d0d0d'):
    return f'<div style="position: relative; width: 100%; height: 100%; box-sizing: border-box; overflow-y: auto; overflow-x: hidden; scrollbar-width: none; background: {bg}; color: {fg}; font-family: \'Archivo Narrow\', sans-serif">{inner}</div>'
def q(n,head,body,cta='NEXT',second=None,note=''):
    bars=''.join(f'<span style="flex: 1; height: 3px; border-radius: 2px; background: {"#0d0d0d" if i<n else "rgba(13,13,13,0.15)"}"></span>' for i in range(9))
    foot=f'<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; gap: 8px">{btn(second,False,False,True) if second else ""}{btn(cta,True,True,True)}</div>'
    return shell(f'''<div style="position: absolute; left: 16px; right: 16px; top: 22px; display: flex; align-items: center; gap: 10px">{BACK}<div style="flex: 1; display: flex; gap: 4px">{bars}</div><span style="{MONO}">{n:02d}/09</span></div>
<div style="position: absolute; left: 16px; right: 16px; top: 84px"><div style="{MONO}">Question {n:02d}{(" · "+note) if note else ""}</div><div style="{BIG} font-size: 46px; margin-top: 8px">{head}</div></div>
<div style="position: absolute; left: 16px; right: 16px; top: 300px; bottom: 110px; overflow-y: auto">{body}</div>{foot}''')
def field(ph,val=''):
    return f'<div contenteditable="true" data-ph="{ph}" style="padding: 18px; background: #F7F7F7; min-height: 120px; box-sizing: border-box; font-size: 19px; line-height: 1.45; outline: none">{val}</div>'
def opt(t,sub='',on=False):
    subdiv=('<div style="font-size: 15px; color: #555; margin-top: 4px">'+sub+'</div>') if sub else ''
    return f'<a href="#" data-opt style="display: block; padding: 16px 0; border-top: 1px solid rgba(13,13,13,0.15); color: #0d0d0d; text-decoration: none"><div style="display: flex; justify-content: space-between; align-items: center"><span style="font-family: \'Archivo Black\', sans-serif; letter-spacing: -0.05em; font-size: 24px; text-transform: uppercase">{t}</span><span class="dot" style="width: 22px; height: 22px; border-radius: 50%; border: 1.5px solid #0d0d0d; background: {"#0d0d0d" if on else "transparent"}"></span></div>{subdiv}</a>'
S={}
S['q01']=q(1,'What should<br>we call our<br>cover star?',field('Your first name','Megan')+f'<div style="{MONO} margin-top: 12px; color: #666">It goes on the cover of your Issue.</div>')
S['q03']=q(3,'What do you<br>want most<br>this year?',''.join(opt(t,s,i==0) for i,(t,s) in enumerate([('Financial freedom','Money that gives me choices'),('A home I love','Space that feels like me'),('Real love','Being chosen, choosing back'),('My own thing','A business, a studio, a name'),('Peace','Calm, health, nothing to prove')])))
S['q04']=q(4,'Pick what<br>feels like<br>her.',f'<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 6px">'+''.join(f'<a href="#" data-pick style="position: relative; display: block; height: 130px; overflow: hidden; {"outline: 3px solid #0d0d0d; outline-offset: 2px;" if i in (0,2,5) else ""}"><img src="{IMG[i]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"></a>' for i in range(9))+'</div>',cta='NEXT · 3 PICKED',note='Your World')
S['q05']=q(5,'How do you<br>want to<br>practice?',''.join(opt(t,s,i==2) for i,(t,s) in enumerate([('Listen','Audio, eyes closed'),('Watch','Immersive video'),('Both','Mix it up')]))+f'<div style="{MONO} margin: 20px 0 10px">How long?</div><div style="display: flex; gap: 8px">{chip("5 min",True)}{chip("10 min")}{chip("20 min")}</div>',note='Audio')
S['q06']=q(6,'How do you<br>want to feel<br>every day?',f'<div style="display: flex; flex-wrap: wrap; gap: 8px">'+''.join(chip(t,t in ('Unbothered','Rich','Chosen'),'#F65AAD') for t in ['Unbothered','Rich','Chosen','Free','Powerful','Soft','Seen','Calm','Magnetic'])+'</div>')
S['q08']=q(8,'Name one<br>thing you<br>already made<br>happen.',field('e.g. I moved cities on my own.','I left the job that made me small.')+f'<div style="{MONO} margin-top: 12px; color: #666">Your first proof. It opens your Issue.</div>',note='Proof')
S['q09']=q(9,'One small<br>step this<br>week?',field('Something small that the future you would do.','Book a viewing for a place by the sea.')+f'<div style="{MONO} margin-top: 12px; color: #666">This becomes your first move.</div>',cta='BUILD MY ISSUE')
S['how']=shell(f'''<div style="padding: 30px 16px 0"><div style="{MONO}">How ISSUE11 works</div><div style="{BIG} font-size: 44px; margin-top: 8px">You're not<br>just making a<br>vision board.</div><div style="font-size: 17px; line-height: 1.4; margin-top: 12px">You're creating an Issue around the person you're becoming.</div></div>
<div style="padding: 18px 16px 120px">'''+''.join(f'<div style="display: flex; gap: 14px; padding: 14px 0; border-top: 1px solid rgba(13,13,13,0.15)"><span style="{MONO} width: 22px">0{i+1}</span><div><div style="{BIG} font-size: 28px; letter-spacing: -0.05em">{h}</div><div style="font-size: 15px; color: #444; margin-top: 4px">{t}</div></div></div>' for i,(h,t) in enumerate([('Desire','Tell us what you want.'),('Imagine','Turn it into images, words and audio.'),('Embody','Practice thinking, feeling and acting like her.'),('Become','Add proof as your future becomes your life.')]))+f'</div><div style="position: absolute; left: 16px; right: 16px; bottom: 30px">{btn("LET’S START")}</div>')
S['meet']=shell(f'''<img src="{ELEVEN_CREAM}" alt="" style="position: absolute; left: 50%; top: 70px; height: 120px; width: auto; transform: translateX(-50%)">
<div style="position: absolute; left: 20px; right: 20px; top: 240px"><div style="{MONO}">Meet</div><div style="{BIG} font-size: 52px; margin-top: 8px">Lucky<br>Star ★</div><div style="font-size: 17px; line-height: 1.45; margin-top: 16px; color: #F5EEE0">Your AI manifestation guide. Lucky Star learns what you're working toward and helps you create your Issue, build your practice and decide what to do next.</div><div style="font-family: 'Archivo Black', sans-serif; font-size: 18px; letter-spacing: -0.03em; margin-top: 14px">You stay in control. Nothing is added or changed unless you approve it.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 12px"><label style="display: flex; gap: 12px; align-items: flex-start; font-size: 14px; line-height: 1.4; color: rgba(245,238,224,0.85); cursor: pointer"><input type="checkbox" id="consent" checked style="width: 20px; height: 20px; accent-color: #F65AAD; margin-top: 2px">Your answers are sent to an AI service to build your Issue. It doesn't train on them or keep them. You can turn AI off in Settings.</label>{wbtn("I'M IN")}<div data-b="PRIVACY" style="text-align: center; {MONO} color: rgba(245,238,224,0.6); cursor: pointer">Read our privacy policy</div></div>''',bg='#0d0d0d',fg='#F5EEE0')
S['reveal']=shell(f'''<img src="{IMG[8]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.15), rgba(0,0,0,0) 30%, rgba(0,0,0,0.7))"></div>
<div style="position: absolute; left: 16px; right: 16px; top: 26px; height: 190px; display: flex; justify-content: center"><img src="{WORDW}" alt="ISSUE11" style="display: block; height: 100%; width: auto"></div>
<div style="position: absolute; left: 16px; right: 16px; top: 228px; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.7); display: flex; justify-content: space-between; {MONO} color: #fff"><span>Vol. 01</span><span>Autumn 2026</span></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; color: #fff; display: flex; flex-direction: column; gap: 14px"><div style="{MONO}">Your first Issue is ready</div><div style="{BIG} font-size: 58px">The Megan<br>Issue</div><div style="font-size: 16px; line-height: 1.4">Financial freedom · A home by the sea · Unbothered</div>{wbtn("OPEN MY ISSUE")}</div>''',bg='#0d0d0d',fg='#fff')
S['notif']=shell(f'''<div style="position: absolute; left: 50%; top: 120px; transform: translateX(-50%) rotate(-6deg)"><span style="position: relative; display: block; width: 120px; height: 120px; border-radius: 33px; overflow: hidden; background: #F5EEE0; border: 3px solid #fff; box-shadow: 0 6px 14px rgba(0,0,0,0.25)"><img src="{LOGO11}" alt="" style="position: absolute; left: 50%; top: 50%; height: 76%; transform: translate(-50%,-50%)"></span></div>
<div style="position: absolute; left: 20px; right: 20px; top: 300px; text-align: center"><div style="{MONO}">One gentle nudge a day</div><div style="{BIG} font-size: 44px; margin-top: 10px">Get your<br>issue every<br>morning?</div><div style="font-size: 16px; line-height: 1.4; margin-top: 14px; color: #444">A line from your Issue and tonight's session. No spam, ever.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 10px">{btn("YES, EVERY MORNING")}<div data-b="NOT NOW" style="text-align: center; {MONO} cursor: pointer; padding: 10px">Not now</div></div>''')
S['paywall']=shell(f'''<div style="position: relative; height: 420px; overflow: hidden"><img src="{IMG[2]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><img src="{ELEVEN_W}" alt="" style="position: absolute; left: 50%; top: 50%; height: 300px; transform: translate(-50%,-50%); filter: drop-shadow(0 10px 30px rgba(0,0,0,0.25))"><a href="#" aria-label="Close" data-b="CLOSE" style="position: absolute; right: 16px; top: 22px; display: flex; width: 40px; height: 40px; border-radius: 50%; align-items: center; justify-content: center; color: #fff; {GLASS}"><svg width="14" height="14" viewBox="0 0 14 14" stroke="currentColor" stroke-width="1.8"><path d="M1 1l12 12M13 1L1 13"/></svg></a></div>
<div style="padding: 18px 16px 0"><div style="{MONO}">ISSUE11 Membership</div><div style="{BIG} font-size: 40px; margin-top: 6px">Keep becoming<br>her.</div><div style="font-size: 15px; line-height: 1.5; margin-top: 10px">Your Issue, every Audio session, Scribe, Your World and new pages every month.</div>
<div style="display: flex; gap: 8px; margin-top: 16px"><a href="#" data-plan style="flex: 1; padding: 14px; border: 3px solid #0d0d0d; color: #0d0d0d; text-decoration: none"><div style="{MONO}">Yearly</div><div style="font-family: 'Archivo Black', sans-serif; font-size: 22px; margin-top: 6px">PRICE TBD</div></a><a href="#" data-plan style="flex: 1; padding: 14px; border: 1px solid rgba(13,13,13,0.2); color: #0d0d0d; text-decoration: none"><div style="{MONO}">Monthly</div><div style="font-family: 'Archivo Black', sans-serif; font-size: 22px; margin-top: 6px">PRICE TBD</div></a></div>
<div style="font-size: 12px; color: #666; line-height: 1.4; margin-top: 10px">Renews automatically until cancelled. Cancel anytime in Settings. (Final wording, prices and any trial: Revenue + Megan.)</div></div>
<div style="padding: 14px 16px 30px; display: flex; flex-direction: column; gap: 10px">{btn("CONTINUE")}<div style="display: flex; justify-content: center; gap: 16px; {MONO} font-size: 10px; color: #555"><span data-b="RESTORE" style="cursor: pointer">Restore</span><span>Terms</span><span>Privacy</span></div></div>''')
S['write']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 22px 16px 0">{BACK}<span style="{MONO}">Scribe · Oct 03 · P.08</span></div>
<div style="padding: 14px 16px 0"><div style="{MONO} color: #666">Today's prompt</div><div style="{BIG} font-size: 34px; margin-top: 6px">Who is she, one<br>year from now?</div></div>
<div contenteditable="true" style="margin: 16px; min-height: 360px; font-size: 19px; line-height: 1.5; outline: none">She wakes up before her alarm. The light comes in off the water. <span style="background: #FCD2DD">She doesn't check her bank balance anymore</span>; she checks in with herself.<span style="display: inline-block; width: 2px; height: 22px; background: #F65AAD; vertical-align: -4px; margin-left: 2px"></span></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; gap: 8px">{btn("SAY IT INSTEAD",False,False,True)}{btn("SAVE TO MY ISSUE",True,False,True)}</div>''')
S['proof']=shell(f'''<div style="display: flex; justify-content: space-between; align-items: center; padding: 22px 16px 0">{BACK}<span style="{MONO}">Add proof</span></div>
<div style="padding: 14px 16px 0"><div style="{MONO} color: #666">You wrote, 6 months ago</div><div style="font-family: Georgia, serif; font-size: 22px; line-height: 1.3; margin-top: 8px">“A home by the sea.”</div><div style="{BIG} font-size: 40px; margin-top: 18px">What<br>happened?</div></div>
<div style="padding: 14px 16px 0">{field("Tell it like a headline.","I signed the lease. I can hear the waves.")}<a href="#" data-b="PHOTO" style="display: flex; align-items: center; justify-content: center; height: 110px; margin-top: 10px; border: 1.5px dashed #BDBDBD; color: #666; text-decoration: none; {MONO}">+ Add a photo</a></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px">{btn("ADD PROOF")}</div>''')
S['proofdone']=shell(f'''<img src="{ELEVEN_CREAM}" alt="" style="position: absolute; left: 50%; top: 50%; height: 1000px; transform: translate(-50%,-50%)">
<div style="position: absolute; left: 0; right: 0; bottom: 0; height: 420px; background: linear-gradient(180deg, rgba(212,8,6,0), #D40806 38%)"></div><div style="position: absolute; left: 16px; right: 16px; bottom: 30px; color: #F5EEE0; display: flex; flex-direction: column; gap: 14px"><div style="{MONO}">Proof · Oct 03</div><div style="{BIG} font-size: 64px">It's<br>real.</div><div style="font-size: 17px">Added to your Issue as page 08.</div>{wbtn("SEE IT IN MY ISSUE")}</div>''',bg='#D40806',fg='#F5EEE0')
S['page']=shell(f'''<div style="position: relative; height: 100%"><img src="{IMG[6]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"><div style="position: absolute; inset: 0; background: linear-gradient(180deg, rgba(0,0,0,0.35), rgba(0,0,0,0) 25%, rgba(0,0,0,0) 45%, rgba(0,0,0,0.75))"></div>
<div style="position: absolute; left: 16px; right: 16px; top: 22px; display: flex; justify-content: space-between; align-items: center; color: #fff"><a href="#" aria-label="Back" style="display: flex; width: 44px; height: 44px; border-radius: 50%; align-items: center; justify-content: center; color: #fff; {GLASS}"><svg width="22" height="14" viewBox="0 0 22 14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 7H2M8 1L2 7l6 6"/></svg></a><span style="{MONO}">P.07 / 11</span></div>
<div style="position: absolute; left: 16px; right: 16px; top: 120px; color: #fff"><div style="{MONO}">Feature</div><div style="{BIG} font-size: 60px; margin-top: 8px">The<br>morning<br>she wakes<br>up rich</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 112px; color: #fff; font-size: 17px; line-height: 1.45">6am. Ocean air. Nothing to prove, everything to build.</div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 26px; display: flex; align-items: center; gap: 10px; height: 64px; padding: 0 6px 0 18px; border-radius: 32px; background: #fff; box-shadow: 0 10px 30px rgba(246,90,173,0.25)"><span style="position: relative; display: block; width: 34px; height: 34px; border-radius: 10px; overflow: hidden; background: #F5EEE0; transform: rotate(-6deg); flex-shrink: 0"><img src="{LOGO11}" alt="" style="position: absolute; left: 50%; top: 50%; height: 76%; transform: translate(-50%,-50%)"></span><input id="pageprompt" placeholder="Change this page… e.g. make it softer" style="flex: 1; min-width: 0; border: 0; outline: 0; font-family: 'Archivo Narrow', sans-serif; font-size: 16px; background: transparent"><a href="#" data-b="APPLY" style="display: flex; width: 50px; height: 50px; border-radius: 50%; align-items: center; justify-content: center; background: #F65AAD; color: #0d0d0d">{ARROW}</a></div></div>''',bg='#0d0d0d',fg='#fff')
rows=[('App icon','icons'),('Your ritual','streak'),('Notifications','notif'),('Lucky Star & AI','meet'),('Membership','paywall'),('Privacy policy',''),('Sign out',''),('Delete account','delete')]
S['you']=shell(f'''<div style="padding: 30px 16px 0; display: flex; gap: 14px; align-items: center"><span style="width: 64px; height: 64px; border-radius: 50%; overflow: hidden; position: relative; flex-shrink: 0"><img src="{IMG[9]}" alt="" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover"></span><div><div style="{BIG} font-size: 40px">Megan</div><div style="{MONO} margin-top: 6px">Vol. 01 · 12 day streak</div></div></div>
<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; padding: 22px 16px 6px">'''+''.join(f'<div style="background: #F2F2F2; padding: 12px"><div style="font-family: \'Archivo Black\', sans-serif; font-size: 28px">{n}</div><div style="{MONO} margin-top: 4px">{l}</div></div>' for n,l in [('7','Pages'),('3','Proofs'),('12','Days')])+f'''</div>
<div style="padding: 10px 16px 120px">'''+''.join(f'<a href="#" data-go2="{g}" style="display: flex; justify-content: space-between; align-items: center; padding: 18px 0; border-top: 1px solid rgba(13,13,13,0.12); color: {"#D40806" if t=="Delete account" else "#0d0d0d"}; text-decoration: none; font-family: \'Archivo Black\', sans-serif; font-size: 20px; letter-spacing: -0.03em; text-transform: uppercase">{t}<span style="{MONO}">→</span></a>' for t,g in rows)+'</div>')
S['delete']=shell(f'''<div style="padding: 22px 16px 0">{BACK}</div><div style="padding: 20px 16px"><div style="{MONO} color: #D40806">Delete account</div><div style="{BIG} font-size: 44px; margin-top: 8px">Are you<br>sure?</div><div style="font-size: 16px; line-height: 1.5; margin-top: 14px">This permanently deletes your account, your Issue, Scribe entries, Your World and proofs. It can't be undone. Your App Store subscription is managed by Apple; cancel it there so you're not charged again.</div></div>
<div style="position: absolute; left: 16px; right: 16px; bottom: 30px; display: flex; flex-direction: column; gap: 10px">{btn("DELETE MY ACCOUNT",True,False,False,"background: #D40806;")}<div data-b="KEEP" style="text-align: center; {MONO} cursor: pointer; padding: 10px">Keep my account</div></div>''')
